spring:
  datasource:
    username: {{DB_USER}}
    password: {{DB_PASSWORD}}
    url: jdbc:postgresql://database.nicholaszullo.com:5432/christmas?currentSchema=christmas_nonprod
  server:
    port: 8081
